### ISSUE TITLE
tangd dumps core on Fedora 32

### ISSUE THREAD

**Issue by marusak** [latchset/tang#44] opened 2020-02-25 11:26 UTC
This is happening on the current Fedora 32 image with `tang-7-4.fc32.x86_64`.

How to reproduce:
1. `$ sudo jose jwk gen -i '{"alg":"ES512"}' -o /var/db/tang/newsig.jwk`
2. `$ sudo jose jwk gen -i '{"alg":"ECMR"}' -o /var/db/tang/newexc.jwk`
3. `$ sudo curl -sSf 127.0.0.1/adv`

The last command returns `curl: (52) Empty reply from server` and when I look into journal I see:
```
Feb 25 06:20:17 localhost.localdomain systemd[1]: Started Tang Server (127.0.0.1:45812).
Feb 25 06:20:17 localhost.localdomain kernel: kauditd_printk_skb: 8 callbacks suppressed
Feb 25 06:20:17 localhost.localdomain kernel: audit: type=1130 audit(1582629617.351:617): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=tangd@9-127.0.0.1:80-127.0.0.1:45812 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Feb 25 06:20:17 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=tangd@9-127.0.0.1:80-127.0.0.1:45812 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Feb 25 06:20:17 localhost.localdomain kernel: traps: tangd[29766] general protection fault ip:55ce5a4ad8f2 sp:7ffcb4a05f80 error:0 in tangd[55ce5a4ad000+2000]
Feb 25 06:20:17 localhost.localdomain audit[29766]: ANOM_ABEND auid=4294967295 uid=981 gid=981 ses=4294967295 subj=system_u:system_r:tangd_t:s0 pid=29766 comm="tangd" exe="/usr/libexec/tangd" sig=11 res=1
Feb 25 06:20:17 localhost.localdomain kernel: audit: type=1701 audit(1582629617.375:618): auid=4294967295 uid=981 gid=981 ses=4294967295 subj=system_u:system_r:tangd_t:s0 pid=29766 comm="tangd" exe="/usr/libexec/tangd" sig=11 res=1
Feb 25 06:20:17 localhost.localdomain audit: BPF prog-id=163 op=LOAD
Feb 25 06:20:17 localhost.localdomain kernel: audit: type=1334 audit(1582629617.408:619): prog-id=163 op=LOAD
Feb 25 06:20:17 localhost.localdomain audit: BPF prog-id=164 op=LOAD
Feb 25 06:20:17 localhost.localdomain kernel: audit: type=1334 audit(1582629617.411:620): prog-id=164 op=LOAD
Feb 25 06:20:17 localhost.localdomain kernel: audit: type=1334 audit(1582629617.413:621): prog-id=165 op=LOAD
Feb 25 06:20:17 localhost.localdomain audit: BPF prog-id=165 op=LOAD
Feb 25 06:20:17 localhost.localdomain systemd[1]: Started Process Core Dump (PID 29767/UID 0).
Feb 25 06:20:17 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@9-29767-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Feb 25 06:20:17 localhost.localdomain kernel: audit: type=1130 audit(1582629617.418:622): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@9-29767-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Feb 25 06:20:17 localhost.localdomain systemd[1]: tangd@9-127.0.0.1:80-127.0.0.1:45812.service: Main process exited, code=dumped, status=11/SEGV
Feb 25 06:20:17 localhost.localdomain systemd[1]: tangd@9-127.0.0.1:80-127.0.0.1:45812.service: Failed with result 'core-dump'.
Feb 25 06:20:17 localhost.localdomain kernel: audit: type=1131 audit(1582629617.713:623): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=tangd@9-127.0.0.1:80-127.0.0.1:45812 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Feb 25 06:20:17 localhost.localdomain audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=tangd@9-127.0.0.1:80-127.0.0.1:45812 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Feb 25 06:20:17 localhost.localdomain systemd-coredump[29768]: Process 29766 (tangd) of user 981 dumped core.
                                                               
                                                               Stack trace of thread 29766:
                                                               #0  0x000055ce5a4ad8f2 on_url (tangd + 0x28f2)
                                                               #1  0x00007f42308ac579 http_parser_execute (libhttp_parser.so.2 + 0x4579)
                                                               #2  0x000055ce5a4ad6f0 main (tangd + 0x26f0)
                                                               #3  0x00007f42306ea042 __libc_start_main (libc.so.6 + 0x27042)
                                                               #4  0x000055ce5a4ad7ae _start (tangd + 0x27ae)

```

**Comment by martinpitt** [comment] 2020-02-25 12:33
Moreover, it also crept into RHEL 8.2 now, I'll file a bugzilla.

**Comment by sergio-correia** [comment] 2020-03-02 11:32
This issue was caused by an update in `http-parser`, which required a rebuild of `tang`. Fedora 32 should have an updated package available.

**Comment by martinpitt** [comment] 2020-03-04 16:47
Confirmed! Current F32 works fine again, thanks!

**Comment by marusak** [comment] 2020-03-06 07:34
It crept into Fedora-31 updates-testing as well. I, however, don't see it bodhi (probably looking at a wrong package).

**Comment by martinpitt** [comment] 2020-05-04 05:04
Please close this now (I can't do that myself), this is fixed everywhere now.

**Comment by sergio-correia** [comment] 2020-05-04 11:30
> Please close this now (I can't do that myself), this is fixed everywhere now.

Thanks, I am closing this.

**Closed by sergio-correia** 2020-05-04 11:30 UTC
